# Borrow Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow-service
  template:
    metadata:
      labels:
        app: borrow-service
    spec:
      initContainers:
      - name: init-borrow-db
        image: mysql:8.0
        command:
          - sh
          - -c
          - |
            mysql -h borrow-db -P 3306 -u user -ppassword -e "
              CREATE DATABASE IF NOT EXISTS borrow_service;
              USE borrow_service;
              CREATE TABLE IF NOT EXISTS borrowings (
                id INT AUTO_INCREMENT PRIMARY KEY,
                user_id VARCHAR(36) NOT NULL,
                book_id VARCHAR(36) NOT NULL,
                borrow_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
              );
            "
      containers:
      - name: borrow-service
        image: library/borrow-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKER
          value: "notification-kafka-bootstrap.default.svc:9092"
        - name: KAFKA_USERNAME
          value: ""
        - name: KAFKA_PASSWORD
          value: ""
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_HOST
          value: "borrow-db"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB
          value: "borrow_service"
---
# Borrow Service Service
apiVersion: v1
kind: Service
metadata:
  name: borrow-service
spec:
  selector:
    app: borrow-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP