apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-init-scripts
data:
  create-topics.sh: |
    #!/bin/bash
    set -e
    echo "Waiting for Kafka to be available at kafka-service:9092..."

    MAX_RETRIES=20
    RETRY_DELAY=3
    ATTEMPT=0

    while true; do
      if /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-service:9092 --list > /dev/null 2>&1; then
        echo "Kafka is available."
        break
      fi

      ATTEMPT=$((ATTEMPT + 1))
      if [ "$ATTEMPT" -ge "$MAX_RETRIES" ]; then
        echo "Kafka did not become available in time. Exiting."
        exit 1
      fi

      echo "Kafka not ready yet. Retrying in $RETRY_DELAY seconds..."
      sleep "$RETRY_DELAY"
    done

    echo "Creating topics..."

    /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-service:9092 --create --if-not-exists \
      --topic book.available_reserved --partitions 1 --replication-factor 1

    /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-service:9092 --create --if-not-exists \
      --topic book.due_date_reminder --partitions 1 --replication-factor 1

    /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka-service:9092 --create --if-not-exists \
      --topic book.overdue --partitions 1 --replication-factor 1

    echo "Topics created."
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-create-topics
spec:
  backoffLimit: 4
  template:
    metadata:
      name: kafka-create-topics
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: kafka-init
          configMap:
            name: kafka-init-scripts
            defaultMode: 0755
      containers:
        - name: kafka-topic-creator
          image: bitnami/kafka:4.0
          command: ["/bin/bash", "-c", "/scripts/create-topics.sh"]
          volumeMounts:
            - name: kafka-init
              mountPath: /scripts