# Kafka Cluster (Strimzi)
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: notification
  namespace: default
spec:
  kafka:
    version: 3.5.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

---

# Kafka Topic: book.due_date_reminder
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: book-due-date-reminder
  labels:
    strimzi.io/cluster: notification
  namespace: default
spec:
  partitions: 3
  replicas: 1
  topicName: book.due_date_reminder

---

# Kafka Topic: book.overdue
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: book-overdue
  labels:
    strimzi.io/cluster: notification
  namespace: default
spec:
  partitions: 3
  replicas: 1
  topicName: book.overdue

---

# Kafka Topic: book.available_reserved
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: book-available-reserved
  labels:
    strimzi.io/cluster: notification
  namespace: default
spec:
  partitions: 3
  replicas: 1
  topicName: book.available_reserved