# Persistent Volume for MongoDB
apiVersion: v1
kind: PersistentVolume
metadata:
  name: book-db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/book-db"
---
# Persistent Volume Claim for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# MongoDB Deployment for Book Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-db
spec:
  selector:
    matchLabels:
      app: book-db
  template:
    metadata:
      labels:
        app: book-db
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: book-db-storage
          mountPath: /data/db
      volumes:
      - name: book-db-storage
        persistentVolumeClaim:
          claimName: book-db-pvc
---
# MongoDB Service for Book Service
apiVersion: v1
kind: Service
metadata:
  name: book-db
spec:
  selector:
    app: book-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
